name: Codacy Coverage Reporter

on:
  push:
    branches: [ci/implement-codecov] 
  pull_request:
    branches: [ci/implement-codecov ]  

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Add steps here to set up your environment and run tests
      # For example:
      # - name: Set up Python
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.x'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Run tests and generate coverage
      #   run: |
      #     coverage run -m pytest
      #     coverage xml

      - name: Run Codacy Coverage Reporter Action
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # Adjust the coverage-reports path to match your coverage output file
          coverage-reports: coverage.xml

      - name: Run Codacy Coverage Reporter Script
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          echo "Running Codacy Coverage Reporter"
          bash <(curl -Ls https://coverage.codacy.com/get.sh)

