name: Codacy Coverage Reporter

on:
  push:
    branches: [ci/implement-codecov]
  pull_request:
    branches: [ci/implement-codecov]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install lcov
        run: sudo apt-get install -y lcov
      
      # Example: Build with coverage flags (adjust according to your build system)
      - name: Build with coverage
        run: |
          g++ -fprofile-arcs -ftest-coverage -O0 -g *.cpp -o myprogram
      
      # Example: Run tests (adjust according to your test framework)
      - name: Run tests
        run: ./myprogram
      
      # Generate LCOV report
      - name: Generate coverage report
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
      
      # Debug: List generated files
      - name: List files
        run: |
          ls -R
          find . -name "*.gcda" -o -name "*.gcno"
      
      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.info
