name: Setup and Run Doxygen

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Delete docs Folder
        run: rm -rf docs

      - name: Generate Documentation
        run: doxygen Doxyfile
